GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJpbmFsZGlpaHNhbjA0MDFAZ21haWwuY29tIiwidXNlcm5hbWUiOiJyaW5hbGRpaWhzYW5uIiwiaWF0IjoxNzIxMzU3MzQyLCJleHAiOjE3MjEzNjAzNDJ9.difEoU8kgdk0UUrV1Tygmtulhg7wgSMmGzL8kVq35FA
###
POST http://localhost:3000/user
Content-Type: application/json

{
  "username": "harimuselasaterus",
  "password": "Ihpatt04", 
  "email": "harimuselasaterus@gmail.com",
  "no_hp": "081343567281",
  "referd_kode": "",
  "birthday": "2001-04-04"
}
###

POST http://localhost:3000/login
Content-Type: application/json
    
{
  "email" : "rinaldiihsan0401@gmail.com",
  "password" : "Ihpatt04"
}

###
GET http://localhost:3000/refreshtoken

###
DELETE  http://localhost:3000/logout

###
POST http://localhost:3000/verifyOTP
Content-Type: application/json

{
    "otp": "389332"
}

###
GET http://localhost:3000/detail/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJpbmFsZGlpaHNhbjA0MDFAZ21haWwuY29tIiwidXNlcm5hbWUiOiJyaW5hbGRpaWhzYW5uIiwiaWF0IjoxNzIxMjMwOTY1LCJleHAiOjE3MjEyMzI3NjV9.A0tFM9i6JMOv_Jm07bKm7eIMPATPJ2z4_DpIWLB06Co
###
PUT http://localhost:3000/update/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJpbmFsZGlpaHNhbjA0MDFAZ21haWwuY29tIiwidXNlcm5hbWUiOiJyaW5hbGRpaWhzYW5uIiwiaWF0IjoxNzIxMjMwOTY1LCJleHAiOjE3MjEyMzI3NjV9.A0tFM9i6JMOv_Jm07bKm7eIMPATPJ2z4_DpIWLB06Co
Content-Type: application/json

{
    "username": "rinaldiihsan",
    "email": "rinaldiihsan0401@gmail.com",
    "no_hp": "082284423150",
    "birthday": "2001-04-04"
}

###
POST http://localhost:3000/forgotPassword
Content-Type: application/json

{
    "email": "aldo.210170184@mhs.unimal.ac.id"
}

###
POST http://localhost:3000/changePassword
Content-Type: application/json

{
    "email": "rinaldiihsan0401@gmail.com",
    "password": "password123"
}


###
GET http://localhost:3000/getAddress/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJpbmFsZGlpaHNhbjA0MDFAZ21haWwuY29tIiwidXNlcm5hbWUiOiJyaW5hbGRpaWhzYW4iLCJpYXQiOjE3MjA2Mjk5MDQsImV4cCI6MTcyMDY0MDcwNH0.ZVf75kTqIsg9oHnoUZGrd_v0OZav58a9-FUbPeF6uW0

###
POST http://localhost:3000/addAddress/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJpbmFsZGlpaHNhbjA0MDFAZ21haWwuY29tIiwidXNlcm5hbWUiOiJyaW5hbGRpaWhzYW5uIiwiaWF0IjoxNzIwNjY4MDQzLCJleHAiOjE3MjA2Nzg4NDN9.iUhunu3s3jy_kSbSmHa2AsH_18ekjLlnXdPp5-5cf4g
Content-Type: application/json

{
    "address": "Jl. Sumber Amal LK. X Medannn"
}

###
DELETE http://localhost:3000/deleteAddress/6/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJpbmFsZGlpaHNhbjA0MDFAZ21haWwuY29tIiwidXNlcm5hbWUiOiJyaW5hbGRpaWhzYW4iLCJpYXQiOjE3MjA2Mjk5MDQsImV4cCI6MTcyMDY0MDcwNH0.ZVf75kTqIsg9oHnoUZGrd_v0OZav58a9-FUbPeF6uW0

###
PUT http://localhost:3000/updateAddress/6/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJpbmFsZGlpaHNhbjA0MDEwNEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6Imloc2FubiIsImlhdCI6MTcyMDY2NzcwMSwiZXhwIjoxNzIwNjc4NTAxfQ.I8480DVgfQSRfMBzqEZTTZqeBQjCmS6dbxKV9ZQjbP8
Content-Type: application/json

{
    "newAddress": "Jl. Bakti No. 8"
}

###(admin only)
POST http://localhost:3000/createnews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJpbmFsZGlpaHNhbjA0MDEwNEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6Imloc2FubiIsImlhdCI6MTcyMDY2NzcwMSwiZXhwIjoxNzIwNjc4NTAxfQ.I8480DVgfQSRfMBzqEZTTZqeBQjCmS6dbxKV9ZQjbP8
Content-Type: application/json

{
    "judulberita" : "Berita Terbaru",
    "isi_berita" : "Berita Terbaru Hari ini",
    "gambar" : "berita.jpg"
}

###
GET http://localhost:3000/getnews

###
GET http://localhost:3000/getnewsbyjudul/Berita%20Terbaru

###
PUT http://localhost:3000/updatenews/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsZG8xMjEybHNtQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoidWNvayIsImlhdCI6MTcyMDM0MjY0NiwiZXhwIjoxNzIwMzQyNjY2fQ.QsgDEmj1pzU4oZ_nrG7nEiEPwyU-rrq0AcnQAWXpxKY
Content-Type: application/json

{
    "judulberita" : "Berita Terbaru1",
    "isi_berita" : "Berita Terbaru Hari ini1",
    "gambar" : "berita.jpg"
}

###
GET http://localhost:3000/news
Content-Type: application/json

{
    "judulberita": "Berita Terbaru1"
}

###
DELETE http://localhost:3000/deletenews/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJpbmFsZGlpaHNhbjA0MDEwNEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6Imloc2FubiIsImlhdCI6MTcyMDY2NzIyNCwiZXhwIjoxNzIwNjc4MDI0fQ.5XnxB_He1YSbq9Pi3XrqV4s81nwafgevPCdnmIF7l9U

###
GET http://localhost:3000/cart/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJpbmFsZGlpaHNhbjA0MDFAZ21haWwuY29tIiwidXNlcm5hbWUiOiJyaW5hbGRpaWhzYW5uIiwiaWF0IjoxNzIzNjU5MTIwLCJleHAiOjE3MjM2NjIxMjB9.iFDKt_Bq_qSP9r4LRW0QyzB9klCjAOr8SlO4Mg9XSRA

###
POST http://localhost:3000/cart/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtraWtpNjAwMUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImFsZG8iLCJpYXQiOjE3MjA4ODI2MTcsImV4cCI6MTcyMDg4NDQxN30.UwTEOlAo_xscqciycVQFItl_CXt53EA68T-Ipchyjd8
Content-Type: application/json

{
    "product_id": "2",
    "quantity" : "2",
    "price" : "20000",
    "name": "Baju",
    "size" : "M"
}

###
PUT http://localhost:3000/cart/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtraWtpNjAwMUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImFsZG8iLCJpYXQiOjE3MjA4ODI2MTcsImV4cCI6MTcyMDg4NDQxN30.UwTEOlAo_xscqciycVQFItl_CXt53EA68T-Ipchyjd8
Content-Type: application/json

{
    "product_id": "2",
    "quantity" : "3",
    "price" : "10000",
    "name": "Baju",
    "size" : "M"
}

###
DELETE http://localhost:3000/cart/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtraWtpNjAwMUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImFsZG8iLCJpYXQiOjE3MjA4ODI2MTcsImV4cCI6MTcyMDg4NDQxN30.UwTEOlAo_xscqciycVQFItl_CXt53EA68T-Ipchyjd8

